# Generated by Django 2.1.1 on 2019-08-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('harga', models.CharField(max_length=255)),
                ('stok', models.BooleanField()),
                ('lokasi', models.CharField(max_length=255)),
            ],
        ),
    ]
