# Generated by Django 2.1.1 on 2019-08-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produks',
            name='satuan',
            field=models.CharField(default='Box', max_length=255),
        ),
        migrations.AlterField(
            model_name='produks',
            name='harga',
            field=models.IntegerField(),
        ),
    ]
