# Generated by Django 2.1.1 on 2019-08-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190818_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='produks',
            name='urlimg',
            field=models.TextField(default='https://dummyimage.com/vga'),
        ),
    ]
